pathologypixels/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from viewer import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.user_login, name='index'),
    path('viewer/', include('viewer.urls')),
]

viewer/urls.py
from django.urls import path
from viewer import views

app_name = 'viewer'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('main/', views.MainPageView, name='main_page'),
    path('main/cases/<str:organsystem_name>/', views.CasesView, name='cases_page'),
    path('main/cases/<str:organsystem_name>/<int:case_id>/', views.wsi, name='wsi'),
    path('register/', views.registration, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('upload/', views.upload, name='upload'),
    path('upload/', views.cows, name='cows')
]

viewer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    performance = models.ForeignKey('viewer.Performance', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username


class Performance(models.Model):
    num_correct = models.IntegerField(default=0)
    num_incorrect = models.IntegerField(default=0)
    total_answered = models.IntegerField(default=0)

    def __str__(self):
        if self.total_answered == 0:
            return "You have not attempted any questions yet."
        else:
            return (self.num_correct / self.total_answered)


class OrganSystem(models.Model):
    name = models.CharField(max_length=75, default='')
    tutorials = models.ManyToManyField('viewer.Tutorial')

    def __str__(self):
        return self.name


class Tutorial(models.Model):
    name = models.CharField(max_length=75, default='')

    def __str__(self):
        return self.name


class Case(models.Model):
    name = models.CharField('case name', max_length=250, default='')
    diagnosis = models.ForeignKey('viewer.Diagnosis', on_delete=models.SET_NULL, null=True)
    history = models.CharField('clinical history', max_length=500, default='')
    teach_points = models.TextField('Teaching Points', max_length=2000, default='')

    def get_image_url(self):
        case_name_low = self.name.lower()
        case_name = case_name_low.replace(' ', '_')
        case_name_dzi = case_name + '/' + case_name + '.dzi'
        return settings.STATIC_URL_2 + 'images/' + case_name_dzi

    def get_image_thumb(self):
        case_name_low = self.name.lower()
        case_name = case_name_low.replace(' ', '_')
        return settings.STATIC_URL_2 + 'images/' + case_name + '/thumb.PNG'

    def __str__(self):
        return str(self.id) + ': '+self.name


class Diagnosis(models.Model):
    text = models.CharField('diagnosis', max_length=200, default='')

    def __str__(self):
        return self.text


class Quiz(models.Model):
    name = models.CharField(max_length=250, default='')

    def num_questions(self):
        return self.questions.all().count()

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ManyToManyField('viewer.Quiz', related_name='questions')
    text = models.CharField(max_length=250, default='')

    def __str__(self):
        return self.text


# class Performance(models.Model):
#     user = models.ForeignKey(UserProfileInfo, related_name='user_answer', on_delete=models.CASCADE)
#     case = models.ForeignKey(Case, related_name='case_answer', on_delete=models.CASCADE)
#     answer = models.CharField(max_length=250, default='')
#
#     def submit_answer(self, ans):
#         self.answer = ans
#         self.save()
#
#     def get_absolute_url(self):
#         return reverse("profile")
#
#     def __str__(self):
#         return self.answer

# class UserAnswer(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     answer = models.CharField(max_length=200, default='')
#     is_correct = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.answer


# class UserPerformance(models.Model):
#     user_answer = models.ForeignKey(UserAnswer, on_delete=models.CASCADE)
#     total_attempts = models.IntegerField(default=0)
#     correct_answers = models.IntegerField(default=0)
#     complete = models.BooleanField(default=False)
#     timestamp = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.user.username

viewer/forms.py
from django import forms
from viewer.models import Profile, Question, Case
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Enter your password'}))

    class Meta:
        model = User
        fields =('first_name', 'last_name', 'username', 'email', 'password')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your desired username'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'})
        }


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

# class RegistrationForm(forms.ModelForm):
#     class Meta():
#         model = MyUser
#         fields = '__all__'

# class QuestionForm(forms.ModelForm):
#
#     class Meta():
#         model = Question
#         fields = ('question',)
#
#         widgets = {
#             'title':forms.TextInput(attrs={'class':'textinputclass'}),
#             'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
#         }


class AnswerForm(forms.Form):
    text = forms.CharField(max_length=250, required=True, label='Answer')


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('name', 'diagnosis', 'history', 'teach_points')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control autocomp', 'placeholder': 'Enter the name of your case'}),
            'diagnosis': forms.TextInput(attrs={'class': 'form-control',
                                                'placeholder': 'Enter the associated diagnosis for your case'}),
            'history': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the clinical history'}),
            'teach_points': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your teaching points'})
        }

    file = forms.FileField()


class EditCaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('name',)

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control autocomp',
                                           'placeholder': 'Enter the name of your case'}),
        }

viewer/views.py
#Python

#Django

#Own

from django.shortcuts import render
from viewer.models import User, Case, Profile, OrganSystem, Tutorial, Diagnosis, Performance
from viewer.forms import UserForm, UserProfileInfoForm, AnswerForm, UploadFileForm, EditCaseForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import authenticate, login, logout, get_user
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.views.generic import View, TemplateView, ListView, DetailView, CreateView


class TestView(TemplateView):
    template_name = 'viewer/wsi.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'BASIC INJECTION'
        return context


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return render(request, 'viewer/profile.html', {"username": username})

        else:
            print("Someone tried to log in and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'viewer/base.html', {})


@login_required
def user_logout(request):
    logout(request)
    return render(request, 'viewer/base.html', {})


@login_required
def MainPageView(request):
    organsystem_name = request.GET.get("organsystem")
    organsystem = OrganSystem.objects.get(name=organsystem_name)
    tutorials = organsystem.tutorials.all()
    return render(request, 'viewer/main.html', context={'organsystem': organsystem, 'tutorials': tutorials})



# class MainPageView(LoginRequiredMixin, TemplateView):
#     template_name = 'viewer/main.html'
#     model = OrganSystem
#     # login_url = '/'
#     # redirect_field_name = 'viewer/base.html'
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['inject_me'] = 'BASIC INJECTION'
#         return context
#     # dispatch is called when the class instance loads
#     def dispatch(self, request, *args, **kwargs):
#         self.year = kwargs.get('year', "any_default")
#     # other code
#     # needed to have an HttpResponse
#     return super(MainPageView, self).dispatch(request, *args, **kwargs)
# def main_page(request):
#     return render(request, 'viewer/main.html')


@login_required
def CasesView(request, organsystem_name):
    organsystem = OrganSystem.objects.get(name=organsystem_name)
    case_list = Case.objects.all().order_by('id')
    print('goodbye')
    return render(request, 'viewer/cases.html', context={'organsystem': organsystem, 'case_list': case_list})


# class CasesView(LoginRequiredMixin, ListView):
#     model = Case
#     template_name = 'viewer/cases.html'
#     context_object_name = 'case_list'
#
#     def get_queryset(self):
#         return Case.objects.all()

# def cases_page(request):
#     case_list = Case.objects.all()
#     return render(request, 'viewer/cases.html', context={'case_list':case_list})

# @login_required
# class WSIView(LoginRequiredMixin, DetailView):
#     model = Case
#     template_name = 'viewer/wsi.html'


@login_required
def wsi(request, organsystem_name, case_id):
    case = Case.objects.get(pk=case_id)
    case_name_low = case.name.lower()
    case_name = case_name_low.replace(' ', '_')
    case_name_dzi = case_name + '/' + case_name + '.dzi'
    case_dx = case.diagnosis.text

    user = get_user(request)
    profile = Profile.objects.get(user=user)
    performance = profile.performance

    diagnoses = []
    for diagnosis in Diagnosis.objects.all():
        diagnoses.append(diagnosis.text)

    if request.method == 'GET':
        answer_form = AnswerForm()
        answered = False
        answer = ''

    if request.method == 'POST':
        answer_form = AnswerForm(data=request.POST)
        answered = True

        if answer_form.is_valid():
            answer = answer_form.cleaned_data['text']
            answer_form = AnswerForm(initial={'text': answer})
        else:
            print(answer_form.errors)

    return render(request, 'viewer/wsi.html', context={'dx': case_name, 'dx_dzi': case_name_dzi, 'case': case,
                                                       'answer_form': answer_form, 'answered': answered,
                                                       'teach_points': case.teach_points, 'diagnoses': diagnoses,
                                                       'case_dx': case_dx, 'answer': answer})


@login_required
def upload(request):

    diagnoses = []
    for diagnosis in Diagnosis.objects.all():
        diagnoses.append(diagnosis.text)

    cases = []
    for case in Case.objects.all():
        cases.append(case.name)

    if request.method == 'POST':
        upload_form = UploadFileForm()
        edit_case_form = EditCaseForm(data=request.POST)
        selected = True
        if edit_case_form.is_valid():
            selected_name = edit_case_form.cleaned_data['name']
            selected_case = Case.objects.get(name=selected_name)
    elif request.method == 'GET':
        upload_form = UploadFileForm()
        edit_case_form = EditCaseForm()
        selected = False
        selected_case = ''

    return render(request, 'viewer/upload.html', context={'upload_form': upload_form, 'edit_form': edit_case_form,
                                                          'diagnoses': diagnoses, 'cases': cases,
                                                          'selected_case': selected_case, 'selected': selected})


@login_required
def profile(request):
    user = get_user(request)
    username = user.username
    profile = Profile.objects.get(user=user)
    performance = profile.performance
    return render(request, 'viewer/profile.html', context={"username": username, "performance": performance})


@login_required
def cows(request):
    pass

# def submit_answer(request):
#     form = forms.AnswerForm()
#
#     if request.method == 'POST':
#         form = forms.AnswerForm(request.POST)
#
#         if form.is_valid():
#             pass
#
#     return render(request, 'viewer/wsi.html', context={'form': form})
#


def registration(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            Profile.objects.create(user=user)

            registered = True

        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, 'viewer/registration.html',
                  context={'user_form': user_form, 'registered': registered})

templates/viewer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head> {% block head %}
    <meta charset="utf-8">
    <title>PathologyPixels</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="imageviewer.css"  rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- <script src="jquery.js"></script>
    <script src="imageviewer.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    {% endblock %}</head>
  <body style="background-color: whitesmoke;">
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'viewer:login' %}">PathologyPixels</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="">About <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Organ Systems
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Bone and Soft Tissue</a>
              <a class="dropdown-item" href="#">Breast</a>
              <a class="dropdown-item" href="#">Cytopathology</a>
              <a class="dropdown-item" href="/viewer/main?organsystem=Dermatopathology">Dermatopathology</a>
              <a class="dropdown-item" href="#">Gastrointestinal</a>
              <a class="dropdown-item" href="#">Genitourinary</a>
              <a class="dropdown-item" href="/viewer/main?organsystem=Gynecologic Pathology">Gynecologic</a>
              <a class="dropdown-item" href="#">Head and Neck</a>
              <a class="dropdown-item" href="#">Hematopathology</a>
              <a class="dropdown-item" href="#">Neuropathology</a>
              <a class="dropdown-item" href="#">Renal</a>
              <a class="dropdown-item" href="#">Thoracic</a>
              <a class="dropdown-item" href="#"></a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/viewer/upload/">Upload/Edit Content</a>
              <a class="dropdown-item" href="/viewer/cows/">COWs</a>
            </div>
          </li>
        </ul>
        {% if user.is_authenticated == False %}
        <form class="form-inline my-2 my-lg-0" action="{% url 'viewer:login' %}" method="POST">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="text" name='username' placeholder="Username">
          <input class="form-control mr-sm-2" type="text" name='password' placeholder="Password">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
        </form>
        {% else %}
        <form class="form-inline">
          <a class="btn btn-outline-success" type="button" href="{% url 'viewer:profile' %}" style="margin-right: 10px">Profile</a>
          <a class="btn btn-md btn-outline-light" type="button" href="{% url 'viewer:logout' %}">Logout</a>
        </form>
        {% endif %}
      </div>
    </nav>

<!-- Jumbotron -->

    <div class="jumbotron jumbotron-fluid" style="background: url({% static 'images/pink-header.png' %}) center / cover;">
      <div class="container-fluid">
        {% block body_block %}
        <h1 class="display-4">Welcome, we are under construction!</h1>
        <p class="lead">This website contains educational content designed to supplement surgical pathology training.</p>
        {% endblock %}
      </div>
    </div>

    {% block body_block_two %}
    {% if user.is_authenticated == False %}
    <div  class="container-fluid">
      <div class="row">
        <div class="col-lg-5"">
          <h2 style="text-align: center; color: pink">------Returning Users------</h2>
          <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name='username' placeholder="Username" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name='password' placeholder="Password" required>
            </div>
            <div class="form-group">
              <input type="submit" class="form-control" value="Login" style="background: pink">
            </div>
          </form>
        </div>
        <div class="col-lg-5 offset-1">
          <h2 style="text-align: center; color: purple"> ------New Users------ </h2>
          <a type="button" class="btn btn-primary btn-lg btn-block" href="{% url 'viewer:register' %}" style="background: purple">Register</a>
        </div>
      </div>
    </div>

    {% endif %}
    {% endblock %}

  </body>
</html>

templates/viewer/cases.html
{% extends 'viewer/base.html' %}
{% load static %}

{% block body_block %}
    <h1 style='font:'> {{ organsystem.name }} </h1>
{% endblock %}

{% block head %}
    {{block.super}}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
{% endblock head %}

{% block body_block_two %}
<style>
.demo-card-wide.mdl-card {
}
.demo-card-wide > .mdl-card__title {
  color: white;
  height: 176px;
}

.mdl-card__title-text {
    background-color: rgba(0, 0, 0, 0.7);
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 5px;
    padding-bottom: 5px;
}

.demo-card-wide > .mdl-card__menu {
  color: #fff;
}
.mdl-card__actions {
    display: flex;
    justify-content: flex-end;
}
</style>

<div class="mdl-grid">
  {% if case_list %}
    {% for case in case_list %}
    <div class="demo-card-wide mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
      <div class="mdl-card__title" style="background: url({{ case.get_image_thumb }}) center / cover;">
        <div class="mdl-card__title-text">
            Case {{case.id}}
        </div>
      </div>
      
      <div class="mdl-card__supporting-text">
        {{ case.history }}    
      </div>
      
      <div class="mdl-card__actions mdl-card--border">
        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="/viewer/main/cases/{{ organsystem.name }}/{{ case.id }}/" target="_blank">
          Go To Case
        </a>
      </div>
      <div class="mdl-card__menu">
      </div>
    </div>
    {% endfor %}
  {% endif %}

</div>
{% endblock %}

templates/viewer/cows.html
{% extends 'viewer/base.html' %}
{% load static %}

templates/viewer/upload.html
{% extends 'viewer/base.html' %}
{% load static %}

{% block head %}
    <meta charset="utf-8">
    <title>PathologyPixels</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="imageviewer.css"  rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script
      src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
      crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
{% endblock %}

{% block body_block %}
    <h1> Upload </h1>
    <h2> Add and edit new content here! </h2>
{% endblock %}

{% block body_block_two %}
    <div class="container-fluid" style="margin:20px">
        <div class="row">
            <div class="col-lg-5" style="border:2px solid black; border-radius:25px; padding:5px; background:#ffe0fa;">
                <h2>Add New Content</h2>
                <p>Use this form if you are entering a brand new case into the database</p>
                <div class="form-group">
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {{ upload_form.as_p }}
                        <input type="submit" name="answ" value="Upload">
                    </form>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1" style="border:2px solid black; border-radius:25px; background:#f0c8f7">
                <h2>Edit Existing Content</h2>
                <p>Use this form is you editing a case that already exists in the database</p>
                <div class="form-group">
                    {% if selected %}
                        {{ selected_case }}
                    {% else %}
                        <form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            {{ edit_form.as_p }}
                            <input type="submit" name="answ" value="Select">
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    var list = {{ diagnoses |safe }};
    var list2 = {{ cases |safe }};
    $("#id_diagnosis").autocomplete({source: list, minLength:3});
    $(".autocomp").autocomplete({source: list2, minLength:3});
    </script>
    <script src="{% static 'js/wsi.js' %}"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}

templates/viewer/wsi.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/wsi.css' %}" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.5.1.js"
      integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
      crossorigin="anonymous">
    </script>
  </head>
  <body>

    <!-- Container for entire page -->

    <div class="wsi-container h-md-100 align-items-center" style="background: url({% static 'images/pink-background.png' %}) center / cover;">

    <!-- First Half -->
      <div id="upper" class="text-black section">
        <div class="section-title">Clinical History</div>
        <div id="hx" class="section-text">
          <p>{{ case.history }}</p>
        </div>
      </div>
        
      <div id="submit" class="section" style="text-align: left">
        {% if not answered %}<div class="section-title">Answer</div>{% endif %}
        <div id="answer" class="section-text" style="padding-top: 5px;">
            {% if answered %}
              {% if answer == case_dx %}
                <h4 style="color:green">Correct!</h4>
                <h4>Answer: {{case.diagnosis.text}}</h4>
              {% else %}
                <h4 style="color:red">Incorrect.</h4>
                <h4>Answer: {{case.diagnosis.text}}</h4>
              {% endif %}
            
              <h3><u>Explanation</u></h3>
              {{ teach_points }}
            {% else %}
              <form enctype="multipart/form-data" method="POST">
                <div class="form-group">
                  {% csrf_token %}
                  {{ answer_form.text }}
                  <input type="submit" name="answ" value="Submit">
                </div>
              </form>
            {% endif %}
        </div>
      </div>


      <!-- Second Half -->

      <div id="secondHalf" class="bg-black">
          <div class="d-md-flex align-items-center justify-content-center osd-container">
            <div id="center" style="width: 100%; height: 100%;">
                <script src="{% static 'js/openseadragon/openseadragon.min.js' %}"></script>
                <script src="{% static 'js/openseadragon/openseadragon-scalebar.js' %}"></script>
                <script type="text/javascript">
                  var viewer = OpenSeadragon({
                    id: "center",
                    prefixUrl: "{% static "js/openseadragon/images/" %}",
                    tileSources: "{{ case.get_image_url }}",
                    showNavigator: true,
                    zoomPerScroll:  2,
                    zoomPerClick: 1.0
                      });
                 viewer.scalebar({
                    pixelsPerMeter: 1000000,
                    xOffset: 10,
                    yOffset: 10,
                    barThickness: 3,
                    color: '#555555',
                    fontColor: '#333333',
                    backgroundColor: 'rgba(255, 255, 255, 0.5)',
                      });
                </script>
            </div>
          </div>

      </div>

  </body>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>var list = {{ diagnoses |safe }};
  $("#id_text").autocomplete({source: list, minLength:3});</script>
  <script src="{% static 'js/wsi.js' %}"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">



</html>